# Generated by Django 5.1.4 on 2024-12-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_brand_brand_id_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug', null=True, unique=True),
        ),
    ]
