# Generated by Django 5.1.4 on 2024-12-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
